apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prodssd-apps
  labels:
    lauckserv.io/environment: prodssd
    lauckserv.io/category: app-set
spec:
  generators:
    - git:
        repoURL: https://github.com/lauckserv/ops-cluster-production
        revision: HEAD
        directories:
          - path: apps/**/*
  template:
    metadata:
      name: "prodssd-{{path.basename}}"
      labels:
        lauckserv.io/environment: prodssd
        lauckserv.io/category: app
    spec:
      project: "{{ path[1] }}-apps"
      source:
        repoURL: https://github.com/lauckserv/ops-cluster-production
        path: "{{ path }}"
        targetRevision: main
        helm:
          releaseName: "{{path.basename}}"
          valueFiles:
            - values.yaml
      destination:
        server: https://192.168.225.12:6443
        namespace: "{{ path[2] }}"
      ignoreDifferences:
        - group: "*"
          kind: "Deployment"
          jsonPointers:
            - /spec/template/spec/hostUsers
      syncPolicy:
        # automated:
        #   prune: true
        #   selfHeal: true
        syncOptions:
          - CreateNamespace=true
