apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: production-apps
  labels:
    lauckserv.io/environment: production
    lauckserv.io/category: app-set
spec:
  generators:
    - git:
        repoURL: https://github.com/lauckserv/ops-cluster-production
        revision: HEAD
        directories:
          - path: apps/**/*
  template:
    metadata:
      name: "{{path.basename}}"
      labels:
        lauckserv.io/environment: production
        lauckserv.io/category: app
    spec:
      project: "{{ path[1] }}-apps"
      source:
        repoURL: https://github.com/lauckserv/ops-cluster-production
        path: "{{ path }}"
        targetRevision: main
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://rancher.lauckserv.net/k8s/clusters/c-m-d25gnqct
        namespace: "{{ path[2] }}"
      ignoreDifferences:
        - group: "*"
          kind: "Deployment"
          jsonPointers:
            - /spec/template/spec/hostUsers
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
