apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: production-apps
  labels:
    lauckserv.io/environment: production
    lauckserv.io/category: app-set
spec:
  generators:
    - git:
        repoURL: https://github.com/lauckserv/ops-cluster-production
        revision: HEAD
        directories:
          - path: apps/**/*
  template:
    metadata:
      name: "{{path.basename}}"
      labels:
        lauckserv.io/environment: production
        lauckserv.io/category: "{{path[1]}}"
    spec:
      project: "{{ path[1] }}-apps"
      source:
        helm:
          version: v3
          valueFiles:
            - values.yaml
        path: "{{ path }}"
        repoURL: https://github.com/lauckserv/ops-cluster-production
        targetRevision: main

      destination:
        server: https://rancher.lauckserv.net/k8s/clusters/c-m-d25gnqct
        namespace: "{{ path[2] }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
