apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
