apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: phpipam-external

spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: phpipam-secrets
  data:
  - secretKey: MYSQL_ENV_MYSQL_DB
    remoteRef:
      key: kubernetes/internal/phpipam
      property: mysql_database
  - secretKey: MYSQL_ENV_MYSQL_HOST
    remoteRef:
      key: kubernetes/internal/phpipam
      property: mysql_host
  - secretKey: MYSQL_ENV_MYSQL_ROOT_PASSWORD
    remoteRef:
      key: kubernetes/internal/phpipam
      property: mysql_password
  - secretKey: MYSQL_ENV_MYSQL_USER
    remoteRef:
      key: kubernetes/internal/phpipam
      property: mysql_user