apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wp-dev-external

spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: wp-mysql-secret
  data:

  - secretKey: mysql-secret
    remoteRef:
      key: kubernetes/dev/wp-dev
      property: mysql-secret