apiVersion: v2
appVersion: "6.5.5"
description: A free, open-source website creation platform
name: wp-htpncc
type: application
version: 0.1.0
dependencies:
  - name: wordpress
    version: 22.4.20
    repository: https://charts.bitnami.com/bitnami
