apiVersion: v2
appVersion: 4.1.2
description: Low-code programming for event-driven applications
name: node-red
type: application
version: 3.7.3

dependencies:
  - name: common
    version: 3.7.3
    repository: https://bjw-s-labs.github.io/helm-charts
