version: 3.6.0
appVersion: 1.33.2
type: application
description: Overseerr
apiVersion: v2
name: overseerr

dependencies:
  - version: 3.6.0
    repository: https://bjw-s.github.io/helm-charts
    name: common
