apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wp-justinlauck-user-external
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: wp-justinlauck-usersecrets
    creationPolicy: Owner
  data:
  - secretKey: wordpress-password
    remoteRef:
      key: kubernetes/prod/wordpress-justinlauck
      property: admin_password