apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wp-ohiovalleyband-db-external
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: wp-ohiovalleyband-dbsecrets
    creationPolicy: Owner
  data:
  - secretKey: mariadb-password
    remoteRef:
      key: kubernetes/prod/wordpress-ohiovalleyband
      property: database_password
  - secretKey: mariadb-replication-password
    remoteRef:
      key: kubernetes/prod/wordpress-ohiovalleyband
      property: database_rootpassword
  - secretKey: mariadb-root-password
    remoteRef:
      key: kubernetes/prod/wordpress-ohiovalleyband
      property: database_rootpassword