version: 2.6.1
appVersion: 2.6.1
type: application
dependencies:
  - version: 3.5.1
    repository: https://bjw-s.github.io/helm-charts/
    name: common
description: Heimdall Application Dashboard is a dashboard for all your web applications
apiVersion: v2
name: heimdall
