image:
  repository: linuxserver/heimdall
  pullPolicy: IfNotPresent
  tag: latest

strategy:
  type: Recreate

env:
  # -- Set the container timezone
  TZ: "America/New_York"
  #PUID: 995
  #PGID: 993

service:
  main:
    ports:
      http:
        port: 80

ingress:
  main: 
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
    labels: 
      ingressClassName: "nginx"
    hosts:
      - host: start.lauckserv.net
        paths:
          - path: /
            pathType: Prefix
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: "1m"
    scrapeTimeout: "30s"
    
persistence:
  config:
    accessMode: ReadWriteMany
    enabled: true
    mountPath: /config
    size: 1Gi
    storageClass: nfs-client
    type: pvc
