controllers:
  heimdall:
    enabled: true
    containers:
      heimdall:
        image:
          repository: ghcr.io/linuxserver/heimdall
          pullPolicy: IfNotPresent
          tag: 2.6.3
        strategy:
          type: Recreate
        env:
          TZ: America/New_York
    type: deployment

service:
  heimdall:
    primary: true
    controller: heimdall
    ports:
      http:
        primary: true
        port: 80
        enabled: true
    type: ClusterIP

ingress:
  heimdall:
    className: nginx
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: start.lauckserv.net
        paths:
          - path: /
            pathType: Prefix
            service:
              port: http
              identifier: heimdall

persistence:
  config:
    enabled: true
    accessMode: ReadWriteMany
    path: config
    size: 1Gi
    storageClass: nfs-client
    type: persistentVolumeClaim
