controllers:
  main:
    replicas: 1
    revisionHistoryLimit: 3
    enabled: true
    containers:
      main:
        probes:
          liveness:
            spec:
              failureThreshold: 3
              periodSeconds: 10
              timeoutSeconds: 1
              initialDelaySeconds: 0
            type: TCP
            enabled: true
            custom: false
          readiness:
            spec:
              failureThreshold: 3
              periodSeconds: 10
              timeoutSeconds: 1
              initialDelaySeconds: 0
            type: TCP
            enabled: true
            custom: false
          startup:
            spec:
              failureThreshold: 30
              periodSeconds: 5
              timeoutSeconds: 1
              initialDelaySeconds: 0
            type: TCP
            enabled: true
            custom: false
        image:
          repository: lscr.io/linuxserver/heimdall
          pullPolicy: IfNotPresent
          tag: 2.6.1
        env:
          TZ: America/New_York
        strategy:
          type: Recreate
    type: deployment
    strategy: Recreate
service:
  main:
    primary: true
    ports:
      http:
        port: 80
        primary: true
        enabled: true
    controller: main
    type: ClusterIP
ingress:
  main:
    hosts:
      - paths:
          - service:
              port: http
              identifier: main
            path: /
            pathType: Prefix
        host: start.lauckserv.net
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/proxy-body-size: 500M
    enabled: true
    className: nginx

persistence:
  config:
    globalMounts:
      - readOnly: false
        path: /config
    accessMode: ReadWriteMany
    enabled: true
    size: 1Gi
    storageClass: nfs-client
    type: persistentVolumeClaim
