apiVersion: v2
name: wp-mim
description: WordPress is a widely used open‑source CMS for building and managing websites, powered by PHP and backed by a MySQL‑compatible database.
type: application
version: 4.6.2
appVersion: 6.9.1
dependencies:
  - name: app-template
    version: 4.6.2
    repository: https://bjw-s-labs.github.io/helm-charts
    alias: wordpress