apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: proget-external

spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: proget-secrets
  data:
  - secretKey: SQL_CONNECTION_STRING
    remoteRef:
      key: kubernetes/internal/proget
      property: connection_string
