apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lycyhee-demo-db-external
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: lychee-demo-dbsecrets
    creationPolicy: Owner
  data:
  - secretKey: MARIADB_PASSWORD
    remoteRef:
      key: kubernetes/prod/lychee-demo-db
      property: database_password
  - secretKey: DB_PASSWORD
    remoteRef:
      key: kubernetes/prod/lychee-demo-db
      property: database_password
  - secretKey: MARIADB_USER 
    remoteRef:
      key: kubernetes/prod/lychee-demo-db
      property: database_username
  - secretKey: DB_USERNAME 
    remoteRef:
      key: kubernetes/prod/lychee-demo-db
      property: database_username
  - secretKey: MARIADB_ROOT_PASSWORD
    remoteRef:
      key: kubernetes/prod/lychee-demo-db
      property: database_rootpassword
